pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building project'
                bat 'mvn -f seljen\\pom.xml clean compile'
            }
        }

        stage('Run Selenium Tests') {
            steps {
                echo 'Running Selenium tests'
                bat 'mvn -f seljen\\pom.xml test'
            }
        }
    }
}
